[package]
name = "eiv"
version = "0.2.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.30", features = ["derive"] }
enum-as-inner = "0.6.1"
serde = { version = "1.0.218", features = ["derive", "rc"] }
subenum = "1.1.2"
thiserror = "2.0.11"
typetag = "0.2.19"
